WebApplication6/Controllers/DeliveryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.Controllers
{
    public class DeliveryController : Controller
    {
        public IActionResult DeliveryInfo()
        {
            return View();
        }
    }
}

WebApplication6/Controllers/HomeController.cs
using BSLogic;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;


namespace WebApplication6.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Chek()
        {
            return View("Index");
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplication6/Controllers/OrdersController.cs
using ASP.MagazineVievModel;
using AutoMapper;
using BSLogic;
using DataLogic.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.Controllers
{
    public class OrdersController : Controller
    {
        private Mapper Mapper;
        private MapperConfiguration configuration;
        public OrdersController()
        {
            this.configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<OrderBL, OrderModel>();
                cfg.CreateMap<BuyerBL, BuyerModel>();
            });

            Mapper = new Mapper(configuration);
        }

        public IActionResult AddToOrder(string buyerId, string productId)
        {
            using (var db = new BLogic())
            {
                var model = new MagazineModel()
                {
                    Orders = Mapper.Map<List<OrderModel>>(db.GetOrders()),
                    Buyers = Mapper.Map<List<BuyerModel>>(db.GetBuyers()),
                    Prroducts = Mapper.Map<List<ProductModel>>(db.GetProducts())
                };
                var buffbuyer = from item in model.Buyers
                           where item.Id == Convert.ToInt32(buyerId)
                           select item;
                var buffproduct = from item in model.Prroducts
                                  where item.Id == Convert.ToInt32(productId)
                                  select item;
                db.AddOrder(new OrderBL() { NumberOfOrder = "123141251", Product = buffproduct as ProductBL });

                return View();
            }
        }
    }
}

WebApplication6/Controllers/ProductsController.cs
using BSLogic;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using ASP.MagazineVievModel;
using System.IO;
using DataLogic.Models;


namespace ASP.Controllers
{
    public class ProductsController : Controller
    {
        private Mapper Mapper;
        private MapperConfiguration configuration;
        public ProductsController()
        {
            this.configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<ProductBL, ProductModel>();
                cfg.CreateMap<BuyerBL, BuyerModel>();
            });

            Mapper = new Mapper(configuration);
        }
        public IActionResult Drinks()
        {
            using(var db = new BLogic())
            {
                var buffmodel = Mapper.Map<List<ProductModel>>(db.GetProducts());
                var model1 = from item in buffmodel
                            where item.Catagery == Category.drink
                            select item;
                var model = new MagazineModel() { Prroducts = model1 };
                return View("Catalog", model);
            }
        }
        public IActionResult Food()
        {
            using (var db = new BLogic())
            {
                var buffmodel = Mapper.Map<List<ProductModel>>(db.GetProducts());
                var model1 = from item in buffmodel
                             where item.Catagery == Category.food
                             select item;
                var model = new MagazineModel() { Prroducts = model1, Buyers=Mapper.Map<List<BuyerModel>>(db.GetBuyers()) };
                return View("Catalog", model);
            }
        }
        public IActionResult Catalog(string category)
        {
            ViewBag.ImgWay = @"C:\Users\Kekozavrishe\source\repos\WebApplication6\WebApplication6\wwwroot\BuffImages\";
            using (var db = new BLogic())
            {
                var model = new MagazineModel()
                {
                    Prroducts = Mapper.Map<List<ProductModel>>(db.GetProducts()),
                    Buyers = Mapper.Map<List<BuyerModel>>(db.GetBuyers())
                };
                foreach (ProductModel item in model.Prroducts)
                {
                    Image buff = Image.FromStream(new MemoryStream(item.ProductImg));
                    buff.Save(@$"C:\Users\Kekozavrishe\source\repos\WebApplication6\WebApplication6\wwwroot\BuffImages\{item.ProductName}.jpg");
                }
                return View(model);
            }

        }
    }
}

WebApplication6/Controllers/RegistrationController.cs
using AutoMapper;
using DataLogic.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.Controllers
{
    public class RegistrationController : Controller
    {
        private Mapper Mapper;
        private MapperConfiguration configuration;
        public RegistrationController()
        {
            this.configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<BuyerBL, BuyerModel>();
            });

            Mapper = new Mapper(configuration);
        }
        public IActionResult Registr()
        {
            return View();
        }
        public IActionResult SaveChanges(string email, string name, int phone)
        {
            BuyerBL buyer = new BuyerBL()
            {
                Name = name,
                Email = email,
                Prhome = Convert.ToInt32(phone)
            };
            using(var db = new BSLogic.BLogic())
            {
                db.AddBuyer(Mapper.Map<BuyerBL>(buyer));
            }
            return Redirect("~/Home/Index");
        }
    }
}

WebApplication6/Views/Delivery/DeliveryInfo.cshtml
@{
    ViewData["Title"] = "DeliveryInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>DeliveryInfo</h1>

WebApplication6/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}
@{
    ViewData["Title"] = "Chek";
}

<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="bd-placeholder-img" src="~/Images/carusel2.jpg" width="70" height="300"  aria-hidden="true" focusable="false"/>

            <div class="container">
                <div class="carousel-caption text-start">
                    <h1>Example headline.</h1>
                    <p>Some representative placeholder content for the first slide of the carousel.</p>
                    <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="bd-placeholder-img" width="70" height="100" src="~/Images/Baner.jpg" focusable="false"/>

            <div class="container">
                <div class="carousel-caption">
                    <h1>Another example headline.</h1>
                    <p>Some representative placeholder content for the second slide of the carousel.</p>
                    <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="bd-placeholder-img" width="100" height="100" src="~/Images/Baner.jpg"  focusable="false"/>

            <div class="container">
                <div class="carousel-caption text-end">
                    <h1>One more for good measure.</h1>
                    <p>Some representative placeholder content for the third slide of this carousel.</p>
                    <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

WebApplication6/Views/Products/Catalog.cshtml
@using ASP.MagazineVievModel
@using DataLogic.Models
@using System
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Catalog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model MagazineModel


<div>
    <br />
    <div class="container align-content-center">
        <a asp-action="Drinks" class="btn btn-primary active" role="button" aria-pressed="true">Drinks</a>
        <a asp-action="Food" role="button" class="btn btn-outline-secondary">Food</a>
    </div>
    <br />
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (ProductModel product in Model.Prroducts.ToList())
            {
                <div class="col">
                    <div class="card shadow-sm">
                        <img class="bd-placeholder-img card-img-top" src="~/BuffImages/@string.Format(product.ProductName + ".jpg")" width="100" height="350" preserveAspectRatio="xMidYMid slice" focusable="true"></img>

                        <div class="card-body">
                            <p class="card-text">@product.Cpecific</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a  class="btn btn-sm btn-outline-dark btn-success" >Buy</a>
                                    <a  class="btn btn-sm btn-outline-secondary">Info</a>
                                </div>
                                <section>Price: @product.Price UAH     </section>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <br />
</div>

WebApplication6/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/bootstrap.css" rel="stylesheet">


    <link href="~/css/carousel.css" rel="stylesheet" />
    <style>

    </style>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand">Magazine</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="home" asp-action="Chek">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Products" asp-action="Catalog">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="home" asp-action="container">Delivery</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <svg id="bag" width="40px" height="40px" viewBox="0 0 16 16" class="bi bi-bag" fill="#FFFFFF" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M14 5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5zM1 4v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4H1z" />
                        <path d="M8 1.5A2.5 2.5 0 0 0 5.5 4h-1a3.5 3.5 0 1 1 7 0h-1A2.5 2.5 0 0 0 8 1.5z" />
                    </svg>
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="search">
                    <button class="btn btn-outline-light bg-info " type="submit">Search</button>
                    <button class="btn btn-close-white" type="submit" asp-controller="Registration" asp-action="Registr">Registration</button>
                </form>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
    <footer  class="footer">
        <div id="footer" class=" bg-dark text-center text-white position-relative">
            <div class="container p-4 pb-0">
                <section class="">
                    <form action="">
                        <div class="row d-flex justify-content-center">
                            <div class="col-auto">
                                <p class="pt-2">
                                    <strong>Sign up for our newsletter</strong>
                                </p>
                            </div>
                            <div class="col-md-5 col-12">
                                <div class="form-outline form-white mb-4">
                                    <input type="email" id="form5Example2" class="form-control" />
                                    <label class="form-label" for="form5Example2">Email address</label>
                                </div>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-outline-light mb-4">
                                    Subscribe
                                </button>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                © 2020 Copyright:
                <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
            </div>
        </div>
    </footer>

    <script src="~/js/bootstrap.js"></script>

</body>
</html>

WebApplication6/Views/_set.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{ 
    Layout = "_Layout";
}